git:
  autocrlf: false
jobs:
  include:
  - os: windows
    language: node_js
    node_js: 8
    install:
    - powershell Install-WindowsFeature Net-Framework-Core
    - export PATH=$PATH:";C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319"
    - export MSYS2_ARG_CONV_EXCL="*"
    script:
    - ./build test
    deploy:
      skip_cleanup: true
      verbose: true
      provider: releases
      token: "$GITHUB_TOKEN"
      file:
      - dispatcher_cmd.exe
      - dispatcher_cmd_x64.exe
      - dispatcher_win.exe
      - dispatcher_win_x64.exe
      on:
        repo: 131/dispatcher
        tags: true
