jobs:
  include:
  - os: windows
    language: node_js
    node_js:
    - 8
    before_install:
    - powershell Install-WindowsFeature Net-Framework-Core
    - export PATH=$PATH:";C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319"
    install:
    - cmd.exe "/c make.bat"
    script: skip
    deploy:
      provider: releases
      token: "$GITHUB_TOKEN"
      skip_cleanup: true
      file:
      - dispatcher_cmd.exe
      - dispatcher_cmd_x64.exe
      - dispatcher_win.exe
      - dispatcher_win_x64.exe
      on:
        repo: 131/dispatcher
        tags: true
