#!/bin/bash

set -xe

PATH=$PATH:$(wslpath 'C:\Windows\Microsoft.NET\Framework\v4.0.30319')

csc=Csc.exe

out_win_x86=dispatcher_win.exe
out_cmd_x86=dispatcher_cmd.exe
out_win_x64=dispatcher_win_x64.exe
out_cmd_x64=dispatcher_cmd_x64.exe


rm -f $out_win_x86  $out_cmd_x86  $out_win_x64  $out_cmd_x64

args=(/noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:0  /errorendlocation /preferreduilang:en-US /highentropyva- /reference:C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\mscorlib.dll /reference:C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\System.dll /reference:C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\System.Xml.dll /reference:C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\System.ServiceProcess.dll /filealign:512 /utf8output)

files=(src\\Utils\\Job.cs src\\Utils\\Kernel32.cs src\\Program.cs src\\Properties\\AssemblyInfo.cs src\\Utils\\ProcessExtensions.cs src\\Utils\\ParentProcessUtilities.cs)
echo "${files[@]}"


"$csc" "${args[@]}" /platform:x86 /define:DISPACHER_WIN /target:winexe /out:$out_win_x86 "${files[@]}"
"$csc" "${args[@]}" /platform:x86                       /target:exe    /out:$out_cmd_x86 "${files[@]}"

"$csc" "${args[@]}" /platform:x64 /define:DISPACHER_WIN /target:winexe /out:$out_win_x64 "${files[@]}"
"$csc" "${args[@]}" /platform:x64                       /target:exe    /out:$out_cmd_x64 "${files[@]}"


if [[ $1 == "sign" ]]; then
  signer $out_win_x86 $out_cmd_x86 $out_win_x64 $out_cmd_x64
fi


if [[ $1 == "test" ]]; then
  npm install
  npm ls || true
  cmd.exe /c npm test
fi