name: test
on: [push]
jobs:
  test:
    runs-on: windows-2022
    environment: production
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: bash ./build --build --test
      env:
        MSYS2_ARG_CONV_EXCL: "*"
    - run: powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./tests/packaged/run.ps1

