name: test
on: [push]
jobs:
  test:
    runs-on: windows-2019
    environment: production
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: rsync
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: powershell Install-WindowsFeature Net-Framework-Core
    - run: bash -x ./build --build --test
      env:
        MSYS2_ARG_CONV_EXCL: "*"
    - run: npm test

